<!DOCTYPE html>
<html class="spreadToSpace">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Login</title>
        <head>
            <link rel="stylesheet" type="text/css" href="css/logfor.css"/>
            <link rel="stylesheet" type="text/css" href="css/generic.css"/>
        </head>
        <body class="spreadToSpace">
        <section class="params">
            <div class="login-page">
              <div class="form">
                <form class="login-form" action="/" method="post">
                  <input name="uname" type="text" placeholder="username"/>
                  <input name="pwd" type="password" placeholder="password"/>
                  <input type="submit" value="login" />
                </form>
              </div>
            </div>
        </section>
            <footer >
                <hr/>
                <p class="center">Login form by: Aigars Silkalns</p>
                <p class="center">Code modified by: Patrik Florians</p>
            </footer>
        </body>
</html>
