<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Attendance</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
        <!--===============================================================================================-->
        <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/animate.css/animate.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/select2/dist/css/select2.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/util.css">
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/bootstrap/dist/js/umd/popper.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/jquery/dist/jquery.min.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/select2/dist/js/select2.min.js"></script>
        <!--===============================================================================================-->
        <!-- scalar JS/PHP data -->
        <script type="text/javascript">
            var months=<?php echo json_encode($months); ?>;
            var currentMonthIndex=<?php echo $currentMonthIndex; ?>;
        </script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/js/httpAjaxRequestors.js"></script>
        <script type="text/javascript" src="/js/Spark.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
<body>
    <?php new \attendance\TableGenerator($parser); ?>
</body>
</html>
