<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Attendance</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
        <!--===============================================================================================-->
        <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/animate.css/animate.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/select2/dist/css/select2.min.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/util.css">
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/bootstrap/dist/js/umd/popper.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/jquery/dist/jquery.min.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/node_modules/select2/dist/js/select2.min.js"></script>
        <!--===============================================================================================-->
        <script type="text/javascript" src="/js/Spark.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>
        <header id="headr"> <!-- komplet cely header moze byt dynamicky linkovany -->
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="hlavicka">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse " id="mainNav">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <button class="btn btn-primary">Edit</button>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a href="#" id="login" data-container="body" data-toggle="popover" title="Enter Credentials"
                                data-placement="bottom">
                                    Log In <span class="fas fa-caret-down"></span></a>
                            </li>
                        </ul>
                        <div id="login-form" class="d-none">
                            <form class="navbar-form" method="post" action="#">
                                <div class="form-group">
                                    <input type="text" class="form-control" maxlength ="4" name="uname" placeholder="username"/>
                                    <input type="password" class="form-control" maxlength="4" name="pwd" placeholder="password"/><br/>
                                    <input type="submit" class="btn btn-primary"/>
                                </div>
                            </form>
                        </div>
                    </div>
                </nav>
            </header>
    <div class="limiter"> <!-- attendance table -->
		<div class="container-table100">
            <button class="btn btn-primary marginRight marginBottom-10"><span class="fas fa-angle-left"></span>Previous Month</button>
            <h3 class="marginAuto marginBottom-10 dynamicFont">Monthly Attendance</h3>
            <button class="btn btn-primary marginLeft marginBottom-10">Next Month<span class="fas fa-angle-right"></span></button>
			<div class="wrap-table100">
				<div class="table100">
					<table id="attendanceTab">
						<thead>
							<tr class="table100-head">
								<th class="column1">Day</th>
								<th class="column2">Arrival</th>
								<th class="column3">Departure</th>
								<th class="column4">Hours Worked</th>
								<th class="column5">Shift</th>
								<!--<th class="column6">Total</th>-->
							</tr>
						</thead>
						<tbody>
                            <?php $parser->fillAttendanceTable(); ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div><!-- end of attendance table -->
    <div class="container">
        <div class="row"><!-- row -->
            <div class="col-md-7 col-sm-12">
                <div class="limiter">
                    <div class="container-table100">
                        <h3>Monthly Absences</h3>
                        <div class="wrap-table100">
                            <div class="table100">
                                <table id="absenceTab">
                                    <thead>
                                        <tr class="table100-head">
                                            <th class="column1">Day</th>
                                            <th class="column2">Type</th>
                                            <th class="column3">Hours absent</th>
                                            <th class="column4">Description</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $parser->fillAbsencesTable(); ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- col 2 -->
            <div class="col-md-5 col-sm-12">
                <div class="limiter">
                    <div class="container-table100">
                        <h3>Monthly Summary</h3>
                        <div class="wrap-table100">
                            <div class="table100">
                                <table id="summaryTable">
                                    <thead>
                                        <tr class="table100-head">
                                            <th class="column1">Worked</th>
                                            <th class="column2">Bonus</th>
                                            <th class="column3">Absent</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $parser->fillSummaryTable(); ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- row -->
    </div>
    <div class="limiter"> <!-- attendance table -->
		<div class="container-table100">
            <h3>Monthly Bonuses</h3>
			<div class="wrap-table100">
				<div class="table100">
					<table id="bonusTab">
						<thead>
							<tr class="table100-head">
								<th class="column1">Day</th>
								<th class="column2">ID</th>
								<th class="column3">Bonus Hours</th>
								<th class="column4">Description</th>
								<!--<th class="column6">Total</th>-->
							</tr>
						</thead>
						<tbody>
                            <?php $parser->fillBonusesTable(); ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div><!-- end of attendance table -->
    <footer class="footer" id="footer">
        <hr/>
        <p class="centrovanie lemovanie">Created by
            <a href="mailto:patrikflorians@gmail.com" class="remove-deco"> Patrik Florians </a>2018
            </p>
        <p class="centrovanie lemovanie">Powered by <a class="remove-deco" href="getbootstrap.org">bootstrap</a></p>
    </footer>
    </body>
</html>
